### ISSUE TITLE
您好 这个如何设置称一行只有三个

### ISSUE THREAD

**Issue by Aguang0612** [zhongjhATC/AlbumCameraRecorder#10]
这边我找了很久 没发现能够设置列数的方法 麻烦告知 多谢

**Comment by zhongjhATC** [comment]
https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/multilibrary/src/main/java/com/zhongjh/albumcamerarecorder/settings/api/AlbumSettingApi.java spanCount函数不可以吗
