### ISSUE TITLE
四列设置成三列 求解答

### ISSUE THREAD

**Issue by Aguang0612** [zhongjhATC/AlbumCameraRecorder#11]
大佬 求解答啊 您这个四列怎么设置成三列啊

**Comment by zhongjhATC** [comment]
https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/multilibrary/src/main/java/com/zhongjh/albumcamerarecorder/settings/api/AlbumSettingApi.java spanCount函数不可以吗
