### ISSUE TITLE
关于Android资源索引的相关问题

### ISSUE THREAD

**Issue by Peachou** [zhongjhATC/AlbumCameraRecorder#12]
作者你好，该仓库的资源索引我看是基于Android本身系统数据库中的数据进行的，该做法的好处显然是比较规范，并且有相应的缩略图之类的还是很不错的。但我发现一个比较奇怪的问题：我的App是支持拍照和录像的，拍照中拍完照放到/sdcard/***某目录后是可以立马被识别的，但视频却不行，我把视频目录和照片目录放一起还是不可以（只能索引到照片，视频不显示）。只有当我把我App中所拍摄的视频重新复制粘帖一下才会被Android系统索引。请问你知道如何解决这种问题嘛？
ps:我用Android的文件管理器也发现这个问题，刚用App录完像的文件是没有缩略图的，只有剪切、粘帖一下才能有缩略图

**Comment by zhongjhATC** [comment]
请问您说的app拍照和录像是基于这个demo操作的吗

**Comment by Peachou** [comment]
> 请问您说的app拍照和录像是基于这个demo操作的吗

不是的，是我自己的App中。不知道为啥系统不自动索引视频，图片倒是可以

**Comment by zhongjhATC** [comment]
然后你的app引用我这个demo进行录像，但是没有自动索引视屏是吗

**Comment by Peachou** [comment]
> 然后你的app引用我这个demo进行录像，但是没有自动索引视屏是吗

是的呢，我发现自带的文件管理器也会有这个问题，就是不显示缩略图，只有再次复制粘帖一下才有该视频的缩略图

**Comment by zhongjhATC** [comment]
好的，最近这个版本我看下这方面问题优化一下

**Comment by Peachou** [comment]
> 好的，最近这个版本我看下这方面问题优化一下

已经解决了，是因为Android系统中常驻一个MediaProvider服务，对应的进程名为android.process.media，此服务用来管理本机上的媒体文件，提供媒体管理服务。在系统开机或者收到外部存储的挂载消息后，MediaProvider会调用MediaScanner，MediaScanner会扫描外部存储中的所有文件，根据文件类型的后缀将文件信息保存到对应的数据库中，供其他APP使用。而我之前直接保存图像或视频的话这个进程是扫描不到所以展示不出来，而这个时候如果保存后广播一下就可以了。
代码如下：
`MediaStore.Images.Media.insertImage(context.getContentResolver(),
                    filePhth,fileName , null);
            context.sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.parse("file://" + file1.getAbsolutePath())));`

**Comment by zhongjhATC** [comment]
非常感谢你提的这个问题。
1.0.18更新版本加上了这个扫描功能
