### ISSUE TITLE
这个控件简直做的真的是太赞了

### ISSUE THREAD

**Issue by FrankLove** [zhongjhATC/AlbumCameraRecorder#15]
功能实现的真是完美啊！！！可不可以增加图片编辑时画笔和文字的大小选择

**Comment by zhongjhATC** [comment]
可以的，等我完善分段录制这方面的功能就着手完善画笔和文字大小

**Comment by FrankLove** [comment]
博主，请问在fragment里面调用
`                    globalSetting
                            .setOnMainListener(errorMessage -> Toast.makeText(getContext(), "自定义失败信息：录音已经达到上限", Toast.LENGTH_LONG).show())
                            .allStrategy(new SaveStrategy(true, "com.zhongjh.cameraapp.fileprovider", "AA/test"))// 设置路径和7.0保护路径等等
                            .imageEngine(new Glide4Engine())    // for glide-V4
                            .maxSelectablePerMediaType(5 - alreadyImageCount, 1 - alreadyVideoCount, 1 - alreadyAudioCount)// 最大10张图片或者最大1个视频
                            .forResult(REQUEST_CODE_CHOOSE);`
接收不到onActivityResult回调是为啥

**Comment by zhongjhATC** [comment]
这个你看看demo有没有回调，如果有，建议仔细看看demo代码漏了哪里

**Comment by FrankLove** [comment]
@zhongjhATC demo里面好像没有在fragment里面使用的实例，这个估计应该我自己处理才行

**Comment by zhongjhATC** [comment]
我是建议没必要所有界面都是fragment的，所以当初只做支持Activity
