### ISSUE TITLE
预览拉伸

### ISSUE THREAD

**Issue by yanfulei** [zhongjhATC/AlbumCameraRecorder#2]
一加手机
型号5T
屏幕比例16：9
预览时倾斜屏幕导致拉伸，前摄像头也会拉伸

**Comment by zhongjhATC** [comment]
好的，这就测试

**Comment by zhongjhATC** [comment]
![](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/demo1/20190311205521.png)

**Comment by zhongjhATC** [comment]
第一张是预览的时候截图，第二张是拍照后的截图……没有拉伸的问题……

都是ONE PLUS 5T的
