### ISSUE TITLE
添加多个音频闪退

### ISSUE THREAD

**Issue by aizyxaizyx** [zhongjhATC/AlbumCameraRecorder#20]
在简单版里边改为上传多个音频后,录第二个音频后确认就闪退了

**Comment by zhongjhATC** [comment]
说明上已经解释了，目前只做单音频，因为涉及定制的东西太多了

**Comment by zhongjhATC** [comment]
下个版本增加无限制音频和视频功能

**Comment by zhongjhATC** [comment]
## 1.1.00X
 - 修复语音播放时，需要点击两次的问题
 - 增加防止抖动（不小心快速多次点击显示多个界面）
 - 增加公共最大值配置,现在可以自由搭配图片上限、视频上限、音频上限，更多例子可以参考demo注释
 - 九宫展示数据也跟着增加公共最大配置
