### ISSUE TITLE
最上面的x按钮点不到，拍照时缩放最大时会卡住死掉

### ISSUE THREAD

**Issue by moyuaxin** [zhongjhATC/AlbumCameraRecorder#22]
华为mate30，android10，

**Comment by zhongjhATC** [comment]
最上面的x按钮点不到,是指拍摄界面吗，你用的是否最新版的代码呢，因为这边跑了几款手机都能关闭。

**Comment by moyuaxin** [comment]
用的最新代码，最上面的那几个都不好点到，图标差不多跑到状态栏哪里了。

**Comment by zhongjhATC** [comment]
有截图看看吗

**Comment by zhongjhATC** [comment]
用华为mate30测试通过，现在最上面的按钮可以点击到了，但是你说的拍摄界面缩放最大时会卡住这个问题我这边重现不了
