### ISSUE TITLE
依赖了项目，xml也没有爆红可以引用到类。运行就报错啊

### ISSUE THREAD

**Issue by tangchao0106** [zhongjhATC/AlbumCameraRecorder#23]
Error inflating class com.zhongjh.progresslibrary.widget.MaskProgressLayout

**Comment by zhongjhATC** [comment]
最新项目其他同学运行没问题额，你跑起过demo吗。  MaskProgressLayout是progresslibrary有引入吗

**Comment by tangchao0106** [comment]
> 最新项目其他同学运行没问题额，你跑起过demo吗。 MaskProgressLayout是progresslibrary有引入吗

解决了，图片引擎那个是必填的类
