### ISSUE TITLE
在列表里面每一个item 包含一个MaskProgressLayout，加载列表时候报这个错啊

### ISSUE THREAD

**Issue by tangchao0106** [zhongjhATC/AlbumCameraRecorder#24]
java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
        at com.zhongjh.progresslibrary.widget.AutoLineFeedLayout.checkLastImages(AutoLineFeedLayout.java:446)

**Comment by tangchao0106** [comment]
这个方法是不是有坑啊，viewHolderAdd没有被初始化
 public void checkLastImages() {
        int mediaCount = (imageList.size() + videoList.size() + this.maskProgressLayout.audioList.size());
        if (mediaCount < maxMediaCount && isOperation) {
            viewHolderAdd.itemView.setVisibility(View.VISIBLE);
        } else {
            viewHolderAdd.itemView.setVisibility(View.GONE);
        }
        updatePosition();
    }

**Comment by zhongjhATC** [comment]
你所说的RecyclerView打开拍摄界面这方面功能还没做过，我这边尝试写个demo看下有什么问题

单个界面的打开单个拍摄是没问题的

**Comment by tangchao0106** [comment]
拍摄视频后根据路径加载，显示在布局的时候报错。走addVideoData-checkLastImages-此时viewHolderAdd没有被初始化。报错

**Comment by zhongjhATC** [comment]
相关功能修复并且优化，关于RecyclerView这方面还没仔细考虑过，因为类似这样的需求太少了

**Comment by tangchao0106** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
