### ISSUE TITLE
相册模块 从全部切换到其他图集  页面一片空白 再切回全部 也是空白

### ISSUE THREAD

**Issue by Tesp** [zhongjhATC/AlbumCameraRecorder#29]
demo是正常的 但是我吧demo代码照搬过来就出现了上述问题  求解答

**Comment by zhongjhATC** [comment]
是否有关权限，provider之类的没设置？

建议把demo的某个Activity搬过来到你的app运行起来，就能知道缺少什么了

**Comment by Tesp** [comment]
把那个MainSImple搬项目里了  然后还是出现上述问题  好奇怪..
是不是跟主题有什么关系啊  因为我看demo里启动相册  标题栏正常居中显示   但是项目里启动的相册 标题栏居上显示 
但是修改主题和demo一致又不起作用..

**Comment by zhongjhATC** [comment]
项目相关sdk环境发一下，或者你把你项目相关环境拷贝，独立出来一个简单的项目，然后把MainSImple搬到这个项目里面看看效果，如果还是有问题，你把该项目发给我我这边帮忙看下

**Comment by zhongjhATC** [comment]
不用了，我找到问题所在了，我先看看

**Comment by zhongjhATC** [comment]
1.1.24X 已经修复该问题
