### ISSUE TITLE
小米6预览视频时闪退

### ISSUE THREAD

**Issue by FadedYu** [zhongjhATC/AlbumCameraRecorder#3]
手机：小米6
使用下载的APK demo体验

1. 在拍完视频后，在九宫格点击预览视频跳转到预览视频界面时，点击开始播放时闪退（估计是找不到视频路径）。

2. 当选中几张图片后，在九宫格点击预览图片时，无论点哪张图片，大图预览总是显示最后的一张。实际上，应该点哪张图片就预览哪张图片的大图。

3. 在预览大图图片中，想要点击右上角圆圈取消选择，虽然确定按钮的数字减少了，但是点击确定返回九宫格时，想要取消选择的图片并没有删除，还在九宫格中。

4. 在配置里最多设置成两个音频时，当录制完第二个音频时候，点击确定时闪退。第二个音频保存不了？

5. 录制音频后，我看了文件管理器并没有这个音频的文件，AA/recorder目录也没有创建。但是列表中可以播放，emmm没有保存到文件去吗？

6. 建议九宫格下的音频列表中，在时间文本框左边添加该音频的名字，名字可以用系统自己添加的，或者可以使用时间格式命名，也可以自定义。没名字的音频感觉怪怪的，而且音频多了不知道是哪个音频。

以上是使用下载APK demo时遇到的问题，还没有时间阅读里面的具体代码。不知道有些问题修复了没有。

**Comment by zhongjhATC** [comment]
非常非常感谢你具体的回复，这些东西我这两天统一解决更新版本给你回复
