### ISSUE TITLE
拍摄录像怎么自定义布局？我想把样式做成微信拍摄一样

### ISSUE THREAD

**Issue by GuangNian10000** [zhongjhATC/AlbumCameraRecorder#32]

**Comment by GuangNian10000** [comment]
我以为是直接可以继承一个类，然后在重写里面的方法就可以了

**Comment by zhongjhATC** [comment]
目前不会，定制性太强了，按钮的点击和长按动画性，显示多图的列表等等都涉及很多

你所想要的微信拍摄其实跟现在是差不多的吧

**Comment by GuangNian10000** [comment]
> 现在不会，定制性太强了，按钮的点击和长按动画性，显示多图的列表等等都涉及很多
> 
> 你所想要的微信拍摄实际跟现在差不多的吧

感谢回复，确实差不多
