### ISSUE TITLE
控件非常好，但是权限控制做的不够精细

### ISSUE THREAD

**Issue by quanqingtouru** [zhongjhATC/AlbumCameraRecorder#34]
如果我不需要录音功能，但是有拍摄功能，还是要求我必须授权录音，这个不是很合理。

**Comment by zhongjhATC** [comment]
这方面有处理，录音功能就只检测录音授权。视频的话会同时检测拍摄和录音权限，因为录制视频也能录制声音进去的

**Comment by quanqingtouru** [comment]
试一下这个控件io.github.lucksiege:pictureselector，没有录音权限，声音也一样可以录进去，奇怪了。

**Comment by quanqingtouru** [comment]
仔细看了一下CameraView，他们的方式不一样，CameraView比较灵活。
