### ISSUE TITLE
录制视频到时间后并没有弹出播放的页面。

### ISSUE THREAD

**Issue by 335759045** [zhongjhATC/AlbumCameraRecorder#35]
这是一个非常好的库。感谢作者，希望再优化一个版本解决录制的问题。

**Comment by 335759045** [comment]
ACTION_MOVE时间到的时候  忘了step++了

**Comment by zhongjhATC** [comment]
你看下最新版的1.1.36X

**Comment by zhongjhATC** [comment]
非常感谢你提的bug，这是上个版本增加功能遗漏了该功能的测试，最新版1.1.37X已经修复并发布

**Comment by 335759045** [comment]
> 非常感谢你提的bug，这是上个版本增加功能遗漏了该功能的测试，最新版1.1.37X已经修复并发布

37x干不下来啊。其他的版本都可以呢

**Comment by zhongjhATC** [comment]
albumCameraRecorderCommon:1.1.37X 改成 common:1.1.37X

这个版本的库名换了

**Comment by 335759045** [comment]
> albumCameraRecorderCommon:1.1.37X 改成 common:1.1.37X
> 
> 这个版本的库名换了



> 

原来如此。感谢
