### ISSUE TITLE
这个控件太棒了，请问如何去掉拍照后图片编辑按钮呢?

### ISSUE THREAD

**Issue by mtboxs** [zhongjhATC/AlbumCameraRecorder#39]
![IMAGE 2022-01-14 19:00:47](https://user-images.githubusercontent.com/96240450/149536745-7466ff4b-136a-4e57-a046-29ea1964a1c3.jpg)

**Comment by zhongjhATC** [comment]
不配置编辑功能即可

**Comment by mtboxs** [comment]
好的，原来需要有一个图片编辑的库，非常感觉您的回复
