### ISSUE TITLE
为什么提示找不到资源文件

### ISSUE THREAD

**Issue by yzxdx159** [zhongjhATC/AlbumCameraRecorder#44]
工程中引入之后,引用组件闪退,提示"java.lang.NullPointerException: itemView.findViewById(R.id.mpvImage) must not be null at com.zhongjh.progresslibrary.apapter.PhotoAdapter$PhotoViewHolder.<init>(PhotoAdapter.kt:443)"

**Comment by zhongjhATC** [comment]
估计是跟item_image.xml冲突有一样的了，我这边把所有layout改名特殊点，下个版本你再试试
或者你现在先把layout的名字换成另外一个看看

**Comment by zhongjhATC** [comment]
已经修复完毕
