### ISSUE TITLE
拍照的路径还是是内部存储路径，导致Glide加载Uri图片崩溃

### ISSUE THREAD

**Issue by xmy1231** [zhongjhATC/AlbumCameraRecorder#45]
![image](https://user-images.githubusercontent.com/10206252/174580085-73030ceb-6898-4a57-b3ce-41c4b84881b1.png)

**Comment by zhongjhATC** [comment]
拍照时存储的路径是内部缓存路径没错的，你这个错误是在demo什么设置下报错的

**Comment by xmy1231** [comment]
@zhongjhATC  已解决了，导入的Glide方式错了。
