### ISSUE TITLE
Demo Apk 闪退

### ISSUE THREAD

**Issue by FWS-86** [zhongjhATC/AlbumCameraRecorder#47]
**问题：**
Demo apk 简单版 长按录制语音后无法正常完成，闪退至添加界面

**测试机型：**
华为mate 30pro max

**具体模块：**
简单版

**具体配置描述：**
简单版，无论全部勾选，还是仅保留录音选项，进入录制界面，长按录制语音，松手后即闪退

**具体错误：**
![1658222807725](https://user-images.githubusercontent.com/9610534/179873591-4f0b6450-2b08-4394-bfec-7ac6fa1ba06e.jpg)

**另：**
无论是长按录制视频还是长按录制语音都需要等待2s左右时间，感觉比较慢，不知道有没有什么好的优化办法？

**Comment by zhongjhATC** [comment]
可以配置长按的预备时间，默认2s，你可以尝试1s的看下

至于这个报错代码，你用的是哪个分支的？我看这边的报错代码行数不一样
![image](https://user-images.githubusercontent.com/39395402/179949837-353e25df-8ce2-476c-9d37-512e794fca62.png)


如果不是androidx分支的，请更换它

**Comment by FWS-86** [comment]
我是直接下载的github上面的demo apk，是不是上面不是最新的

**Comment by zhongjhATC** [comment]
已经更新最新apk，你更新下试下。欢迎star~！

**Comment by FWS-86** [comment]
好的，感谢！
