### ISSUE TITLE
ERROR: Failed to resolve: com.github.zhongjhATC.AlbumCameraRecorder:common:1.0.5

### ISSUE THREAD

**Issue by jelly-lemon** [zhongjhATC/AlbumCameraRecorder#5]
已按要求在 allprojects->repositories 中添加了 maven { url 'https://www.jitpack.io' }。但是无法引用。
ERROR: Failed to resolve: com.github.zhongjhATC.AlbumCameraRecorder:common:1.0.5

**Comment by zhongjhATC** [comment]
这边是我的一个失误，版本迭代后，库改名字了，文档忘记改了

common改为albumCameraRecorderCommon
