### ISSUE TITLE
老兄，运行不起来了

### ISSUE THREAD

**Issue by 957919019** [zhongjhATC/AlbumCameraRecorder#6]
我这儿怎么着都运行不起来，报错如下：
`Android resource compilation failed
Output:  E:\APPWatching\AlbumCameraRecorder-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:910: error: <item> inner element must either be a resource reference or empty.

Command: E:\Base\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\645b862316799e138a0d60093c7de4c5\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        E:\APPWatching\AlbumCameraRecorder-master\app\build\intermediates\res\merged\debug \
        E:\APPWatching\AlbumCameraRecorder-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #2
`
我记得上个版本下载了还能跑起来，不小心删了，重新下了以后不行了，似乎是资源有问题

**Comment by 957919019** [comment]
我看了一下，你上传的代码有一个library文件夹里面都是build文件，是不是上传的时候乱了？

**Comment by zhongjhATC** [comment]
已经修正这个问题了，是增加检查内存泄漏后导致不能运行，不过也删除了library这个文件夹 :)
