### ISSUE TITLE
Android 13 不能使用外部存储权限了，需要兼容一下

### ISSUE THREAD

**Issue by ypfsoul** [zhongjhATC/AlbumCameraRecorder#64]

**Comment by zhongjhATC** [comment]
近期添加兼容

**Comment by zhongjhATC** [comment]
这边用android 13的模拟器运行demo，是可以请求多一个多媒体权限的，你可以拿demo试下，该库是自带权限申请功能

**Comment by ypfsoul** [comment]
> 这边用android 13的模拟器运行demo，是可以请求多一个多媒体权限的，你可以拿demo试下，该库是自带权限申请功能

demo默认跑是没问题的，不过到8月份GooglePlay审核包需要强制设置TARGET_SKD_VERSION到33了，如果demo也改为设置TARGET_SKD_VERSION到33的话，就不能正常运行了，STORAGE的权限会直接denied

**Comment by zhongjhATC** [comment]
哦对，忘记设置targetSDK了，那这个版本调试下

**Comment by zhongjhATC** [comment]
1.1.83X版本已经修复该问题，demo SDK 升级到33现在已经可以正常运行
