### ISSUE TITLE
onActivityResult Deprecated

### ISSUE THREAD

**Issue by cson2701** [zhongjhATC/AlbumCameraRecorder#66]
#### 描述你遇到的问题
`onActivityResult`已经弃用了，有办法用`registerForActivityResult`吗？
另外我发现Demo里的`onActivityResult`IDE并没有提示Deprecated是为什么？

#### 是否使用作者Demo报错
否

**Comment by zhongjhATC** [comment]
因为Demo的是比较低版本的sdk,所以没有提示Deprecated

其次onActivityResult虽然被弃用了,但是效果一样的,区别只是registerForActivityResult更加方便

你依然可以使用registerForActivityResult的,你是哪里碰到困难了呢

**Comment by cson2701** [comment]
谢谢回复，了解了，没有遇到任何问题，我先用着onActivityResult
