### ISSUE TITLE
AppUtil在某些情况下获取包名为空

### ISSUE THREAD

**Issue by zjm8889** [zhongjhATC/AlbumCameraRecorder#67]
> packageInfo.applicationInfo.labelRes这段代码在Androidmanifest.xml通过动态改变android:label设置App名时候（比如通过配置build.gradle文件打多渠道包，每个渠道生成不同的包名）的时候，获取报名为空，解析失败，以下是修改后的代码，作者可以参考下：

        ApplicationInfo appInfo;
        try {
            appInfo = getPackageManager().getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
            String appName = appInfo.loadLabel(getPackageManager()) + "";
            Log.d("稳定、可靠获取App名称", appName);
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by zhongjhATC** [comment]
好的谢谢非常感谢你的建议!
