### ISSUE TITLE
视频清晰度问题

### ISSUE THREAD

**Issue by swallowsonny** [zhongjhATC/AlbumCameraRecorder#7]
在CameraOperation类中，我把这个视频宽度改大了，视频确实清晰些，但是拍出来的视频，一会模糊一会清晰          

 // 这是预览时帧数据的尺寸
//            Camera.Size previewSize = CameraParamUtil.getInstance().getPreviewSize(parameters
//                    .getSupportedPreviewSizes(), 1000, screenProp);
            Camera.Size previewSize = CameraParamUtil.getInstance().getPreviewSize(parameters
                    .getSupportedPreviewSizes(), 1920, screenProp);

            // 这是拍照后的PictureSize尺寸
//            Camera.Size pictureSize = CameraParamUtil.getInstance().getPictureSize(parameters
//                    .getSupportedPictureSizes(), 1200, screenProp);
            Camera.Size pictureSize = CameraParamUtil.getInstance().getPictureSize(parameters
                    .getSupportedPictureSizes(), 1920, screenProp);

**Comment by swallowsonny** [comment]
上面那个是图片的，下面这个是视频的
if (parameters.getSupportedVideoSizes() == null) {
//            videoSize = CameraParamUtil.getInstance().getPreviewSize(parameters.getSupportedPreviewSizes(), 600,
//                    screenProp);
            // fix by sjx
            videoSize = CameraParamUtil.getInstance().getPreviewSize(parameters.getSupportedPreviewSizes(), 1280,
                    screenProp);
        } else {
//            videoSize = CameraParamUtil.getInstance().getPreviewSize(parameters.getSupportedVideoSizes(), 600,
//                    screenProp);
            // fix by sjx
            videoSize = CameraParamUtil.getInstance().getPreviewSize(parameters.getSupportedVideoSizes(), 1280,
                    screenProp);
        }

**Comment by zhongjhATC** [comment]
一会模糊一会清晰是指拍完后，观看过程某个过程清晰，某个过程模糊是吗

**Comment by swallowsonny** [comment]
@zhongjhATC 是的，会不会是对焦没对上

**Comment by swallowsonny** [comment]
@zhongjhATC 拍摄的时候也看得出来这个现象，是改大了那个视频宽度后出现的

**Comment by zhongjhATC** [comment]
一般出现模糊的情况是对焦情况

**Comment by zhongjhATC** [comment]
你是出于什么理由需要修改视频宽度呢？因为这个宽高比例是按照手机的比例来弄的。

我网上搜索的一个具体解释。

在camera的开发中，因为不同手机硬件的原因，所支持的分辨率都不一样，所以在surface view预览的时候需要同时考虑到surface view的大小比例以及camera的画面比例，然而在设置比例尺的时候如若传入不支持的宽高，camera的画面是传递不过来的，所以只能根据手机支持的比例来改变surface大小及画面。注，surfaceveiw比例、camera画面比例、pictrue size比例三者必须一致。
--------------------- 
作者：周奇葩 
来源：CSDN 
原文：https://blog.csdn.net/sung_ll/article/details/72929698 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by swallowsonny** [comment]
因为拍出来的视频清晰度感觉不够，所以想着把这个宽度设置大些，视频会细腻些。修改后拍摄的图片也确实要清晰些

**Comment by zhongjhATC** [comment]
晚上我先按照你贴的代码改下，麻烦能详细贴下是改了哪里的代码吗

我没记错的话，你可以看到里面的代码是根据比例来设置宽高的，如果你仅仅拉宽，高度不变，可能会出现别的问题

**Comment by swallowsonny** [comment]
我clone了demo，只修改了CameraOperation，就是上面图片和视频的宽度那几行，其他的都没动。
有视频的log： 07-05 15:28:57.650 22788-22788/com.zhongjh.cameraviewsoundrecorder I/CameraOperation: setVideoSize    width = 1920height = 1080

**Comment by swallowsonny** [comment]
videoSize = CameraParamUtil.getInstance().getPreviewSize(parameters.getSupportedVideoSizes(), 1280,
screenProp); 这个位置我改成了1280，本来是写的1920的，结果log日志打印的是：
07-05 15:24:29.436 21517-21517/com.zhongjh.cameraviewsoundrecorder I/CameraOperation: setVideoSize    width = 3840height = 2160

**Comment by zhongjhATC** [comment]
我这边看清晰度没有什么问题。。

你看看官方demo的这个
https://github.com/googlesamples/android-Camera2Basic

看看清晰度是否满足你要求？

因为后来我将要把camera升级成camera2

**Comment by swallowsonny** [comment]
好的，谢谢！
