### ISSUE TITLE
apk下载地址无效了

### ISSUE THREAD

**Issue by lingguanjie** [zhongjhATC/AlbumCameraRecorder#70]

**Comment by zhongjhATC** [comment]
我这边点击可以下载哦,gitee地址的源码中有个apk文件地址

**Comment by lingguanjie** [comment]
这个地方点了之后网页：[session-824cc7b5] Route error: ["Access denied", 4]


| |
凌冠杰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年3月14日 16:27 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zhongjhATC/AlbumCameraRecorder] apk下载地址无效了 (Issue #70) |

我这边点击可以下载哦,gitee地址的源码中有个apk文件地址

**Comment by zhongjhATC** [comment]
或者你试试这个源码下面有个apk文件夹

**Comment by lingguanjie** [comment]
ok，这个可以
