### ISSUE TITLE
是否考虑降低kotlin版本

### ISSUE THREAD

**Issue by stars-one** [zhongjhATC/AlbumCameraRecorder#77]
如题,旧项目比较稳定了,用的是1.5.21的kotlin版本,但是此库好像是1.7.x版本,编译apk出现冲突报错

目前我是打算fork一份项目,然后手动降低kotlin版本...

**Comment by zhongjhATC** [comment]
> 如题,旧项目比较稳定了,用的是1.5.21的kotlin版本,但是此库好像是1.7.x版本,编译apk出现冲突报错
> 
> 目前我是打算fork一份项目,然后手动降低kotlin版本...

你可以fork然后单独修改kotlin版本，后面该库有更新的话，你直接更新库即可
