### ISSUE TITLE
GlobalSpec.isCompressEnable() on a null object

### ISSUE THREAD

**Issue by big-guogai** [zhongjhATC/AlbumCameraRecorder#80]
描述你遇到的问题
出现偶发的崩溃bug，暂未复现，只使用了图片选择单张的功能
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.zhongjh.albumcamerarecorder.settings.GlobalSpec.isCompressEnable()' on a null object reference
       at com.zhongjh.albumcamerarecorder.album.ui.MatissFragment.onDestroy(MatissFragment.java:402)

是否使用作者Demo报错
否

期待修复的效果
希望正常运行

**Comment by zhongjhATC** [comment]
感谢反馈，1.1.87X版已经修复
