### ISSUE TITLE
拍照偶现空指针崩溃

### ISSUE THREAD

**Issue by zjm8889** [zhongjhATC/AlbumCameraRecorder#82]
请见附件
![WechatIMG553](https://github.com/zhongjhATC/AlbumCameraRecorder/assets/13343305/fc557239-48fb-485d-b60c-98b164022ca3)

**Comment by zhongjhATC** [comment]
请问具体哪行调用这个错误呢，源码中只有一个地方调用并且已经进行判空处理了

**Comment by zhongjhATC** [comment]
请确定是否用新版代码

**Comment by zjm8889** [comment]
![WeChate75e285d9e7d03ec07d24039531c9901](https://github.com/zhongjhATC/AlbumCameraRecorder/assets/13343305/aa615392-29a1-4b61-8f1e-960fdef8f85c)
bugly上面只体现了这些信息

**Comment by zjm8889** [comment]
我用的是1.1.83版本代码，我现在改成1.1.91版本试下
