### ISSUE TITLE
按照文档，添加了combined:1.1.89X和progresslibrary:1.1.89X库后，xml里添加控件时，没有progresslibrary对应库下内容。

### ISSUE THREAD

**Issue by rcjs** [zhongjhATC/AlbumCameraRecorder#84]
按照文档，添加了implementation 'com.github.zhongjhATC.AlbumCameraRecorder:combined:1.1.89X'，但xml里没有com.zhongjh.progresslibrary.widget.MaskProgressLayout控件可添加，progresslibrary对应库下内容都没有。再添加 implementation 'com.github.zhongjhATC.AlbumCameraRecorder:progresslibrary:1.1.89X'，也没有progresslibrary对应库下内容。
当前gradle为5.4.1，不知道哪里出问题了？

**Comment by zhongjhATC** [comment]
升级最新版1.1.94X看看

**Comment by zhongjhATC** [comment]
最新代码中添加了项目testmave,是可以引入progresslibrary的
