### ISSUE TITLE
滑出按钮范围不会停止录像

### ISSUE THREAD

**Issue by jeremyyu123** [zhongjhATC/AlbumCameraRecorder#87]
长按开启录像后，手指滑出按钮范围后松开，此时不会停止录像

**Comment by zhongjhATC** [comment]
收到，近期修复该问题

**Comment by OliverGarfield** [comment]
@zhongjhATC 请问这个问题修复了吗？

**Comment by zhongjhATC** [comment]
该问题已经修复，如果在最新demo没有改任何配置的情况，还会出现以下情况：
“长按开启录像后，手指滑出按钮范围后松开，此时不会停止录像”

请具体回复改了什么配置
