### ISSUE TITLE
视频拍摄后预览界面

### ISSUE THREAD

**Issue by OliverGarfield** [zhongjhATC/AlbumCameraRecorder#90]
视频拍摄后预览界面是否可以增加显示当前视频时长的功能显示呢

另外打开图库的时候 如果当前使用的是Dracula这个主题，状态栏的文字以及图标颜色是否可以支持修改呢？或者增加打开图库的一个回调类似于拍照的cameraFragment

**Comment by zhongjhATC** [comment]
1. 这个目前只能修改源码
2. 主题可以自定义颜色，可以详细看Demo是怎么引用样式的
