### ISSUE TITLE
使用1.1.104x版本调用forResult不管是code还是回调，都显示白屏呢？

### ISSUE THREAD

**Issue by wangguoqiang1208** [zhongjhATC/AlbumCameraRecorder#94]

**Comment by wangguoqiang1208** [comment]
最新版ide ladybug  gradle 8.9

**Comment by zhongjhATC** [comment]
使用最新版看看demo是否有问题

**Comment by wangguoqiang1208** [comment]
> 使用最新版看看demo是否有问题

demo无法运行，高版本gradle和sdk中有的api被废弃编译不通过

**Comment by zhongjhATC** [comment]
意思是你的gradle是高版本？你改gradle改成你那边的版本，然后demo发给我看下，可以qq群联系。或者改动少的话，你具体改法发给我看下

**Comment by wangguoqiang1208** [comment]
![1732861980482](https://github.com/user-attachments/assets/d778948e-c922-46d8-8c6c-f2e4ba3242d2)
我调试了下，fragment一直为null导致页面空白，是我哪里写错了吗？

**Comment by zhongjhATC** [comment]
具体你要说出改了哪里，最好是在demo基础上修改。这样我才好给你解答问题

**Comment by zhongjhATC** [comment]
使用 from(activity: Activity)方法

**Comment by wangguoqiang1208** [comment]
> 具体你要说出改了哪里，最好是在demo基础上修改。这样我才好给你解答问题

您好，demo在高版本上跑不起来，各种改，最后还是报错的，所以自己写了demo，怎么加Q呢，方便交流知道下吗
![1733383643973](https://github.com/user-attachments/assets/fc9a4325-6b14-45aa-a349-e5be20d77d9c)
