### ISSUE TITLE
MaskProgressLayoutListener中的onItemClose如何获取下标?

### ISSUE THREAD

**Issue by lishiyu1810** [zhongjhATC/AlbumCameraRecorder#95]
在onItemClick中使用mplImageList.getImagesAndVideos().indexOf(multiMediaView)会正确返回,
而在onItemClose使用mplImageList.getImagesAndVideos().indexOf(multiMediaView)会报错
![image](https://github.com/user-attachments/assets/4f5a7b58-c853-4417-9d3e-fa04d0132435)

**Comment by zhongjhATC** [comment]
https://github.com/zhongjhATC/AlbumCameraRecorder/issues/46
请按照这个规范提问题

目前在最新demo中的MainActivity的onItemClose加入mBinding.mplImageList.getImagesAndVideos().indexOf(multiMediaView); 这句代码是完全能获取的
